In [11]:
import pandas as pd
import numpy as np

# Set a random seed for reproducibility
np.random.seed(37) # You can use any integer value here. For quiz put 42

# Generate 25 random names for the 'nombre' column
nombres = [f'Estudiante{i}' for i in range(10)]

# Generate 4 columns of random grades between 0 and 5 with two decimal places
# np.random.uniform generates floats between low (inclusive) and high (exclusive)
parciales = np.round(np.random.uniform(0, 5, size=(10, 4)), 2);

# Create the DataFrame
df = pd.DataFrame({
    'nombre': nombres,
    'parcial1': parciales[:, 0],
    'parcial2': parciales[:, 1],
    'parcial3': parciales[:, 2],
    'parcial4': parciales[:, 3]
})

In [13]:
df

        nombre  parcial1  parcial2  parcial3  parcial4
0  Estudiante0      4.72      2.32      0.96      2.91
1  Estudiante1      3.10      3.42      0.52      3.73
2  Estudiante2      1.41      3.77      3.96      3.14
3  Estudiante3      2.22      4.82      4.49      0.98
4  Estudiante4      2.98      2.87      3.52      4.65
5  Estudiante5      0.26      0.67      0.59      1.82
6  Estudiante6      4.02      4.85      1.66      2.39
7  Estudiante7      0.89      4.51      3.82      0.99
8  Estudiante8      1.83      2.98      0.20      4.12
9  Estudiante9      3.20      0.10      4.03      2.02

In [15]:
df['promedio']=(df['parcial1']*0.20+df['parcial2']*0.20+df['parcial3']*0.20+df['parcial4']*0.40)

In [17]:
df

        nombre  parcial1  parcial2  parcial3  parcial4  promedio
0  Estudiante0      4.72      2.32      0.96      2.91     2.764
1  Estudiante1      3.10      3.42      0.52      3.73     2.900
2  Estudiante2      1.41      3.77      3.96      3.14     3.084
3  Estudiante3      2.22      4.82      4.49      0.98     2.698
4  Estudiante4      2.98      2.87      3.52      4.65     3.734
5  Estudiante5      0.26      0.67      0.59      1.82     1.032
6  Estudiante6      4.02      4.85      1.66      2.39     3.062
7  Estudiante7      0.89      4.51      3.82      0.99     2.240
8  Estudiante8      1.83      2.98      0.20      4.12     2.650
9  Estudiante9      3.20      0.10      4.03      2.02     2.274

In [ ]:
cont=0
for i in df['promedio']:
    if i>=3.75:
        cont+=1 
print(f'')

In [39]:
def funcion():    
    import pandas as pd
    import numpy as np

    # Set a random seed for reproducibility
    np.random.seed(47) # You can use any integer value here. For quiz put 42

    # Generate 25 random names for the 'nombre' column
    nombres = [f'Estudiante{i}' for i in range(10)]

    # Generate 4 columns of random grades between 0 and 5 with two decimal places
    # np.random.uniform generates floats between low (inclusive) and high (exclusive)
    parciales = np.round(np.random.uniform(0, 5, size=(10, 4)), 2);

    # Create the DataFrame
    df = pd.DataFrame({
        'nombre': nombres,
        'parcial1': parciales[:, 0],
        'parcial2': parciales[:, 1],
        'parcial3': parciales[:, 2],
        'parcial4': parciales[:, 3]
    })
    
    df['promedio']=(df['parcial1']*0.20+df['parcial2']*0.20+df['parcial3']*0.20+df['parcial4']*0.40)
    cont=0
    for i in df['promedio']:
        if i>=3:
            cont+=1 
    return f'{cont} personas lograron pasar'

In [41]:
funcion()

'2 personas lograron pasar'

In [42]:
df

        nombre  parcial1  parcial2  parcial3  parcial4  promedio
0  Estudiante0      4.72      2.32      0.96      2.91     2.764
1  Estudiante1      3.10      3.42      0.52      3.73     2.900
2  Estudiante2      1.41      3.77      3.96      3.14     3.084
3  Estudiante3      2.22      4.82      4.49      0.98     2.698
4  Estudiante4      2.98      2.87      3.52      4.65     3.734
5  Estudiante5      0.26      0.67      0.59      1.82     1.032
6  Estudiante6      4.02      4.85      1.66      2.39     3.062
7  Estudiante7      0.89      4.51      3.82      0.99     2.240
8  Estudiante8      1.83      2.98      0.20      4.12     2.650
9  Estudiante9      3.20      0.10      4.03      2.02     2.274